### ISSUE TITLE
Mapped Rbds are not synced into tendrl

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ceph_integration#272]
There are issues with sync when maped rbd are present in the ceph cluster. 

Use below commands to map rbds:

-Create an image-
[ubuntu@magna068 ~]$ rbd create test --size 1G --cluster <cluster name>

-disable features following features fast-diff, object-map, deep-flatten-
[ubuntu@magna068 ~]$ sudo rbd feature disable test fast-diff --cluster <cluster name>
[ubuntu@magna068 ~]$ sudo rbd feature disable test object-map --cluster <cluster name>
[ubuntu@magna068 ~]$ sudo rbd feature disable test deep-flatten --cluster <cluster name>

-map, create an fs and mount the rbd image-
[ubuntu@magna068 ~]$ sudo rbd map test --cluster <cluster name>
/dev/rbd0
[ubuntu@magna068 ~]$ sudo mkfs -t xfs /dev/rbd0

[ubuntu@magna068 ~]$ mkdir test
[ubuntu@magna068 ~]$ sudo mount /dev/rbd0 ~/test

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat @r0h4n @shtripat  When we disable fast-diff it will give one extra error line, Because of parsing sync is not happening properly 
 
rbd --pool rbd --cluster ceph du --image test
warning: fast-diff map is not enabled for test. operation may be slow.
NAME PROVISIONED USED 
test       1024M    0

i have fixed this problem in my librbd PR
https://github.com/GowthamShanmugam/ceph-integration/commit/23a0184b9628963d2a8b5bda6175438fde108711#diff-4acdca69bb0853dd756721408b403221R426
